name: Factions
version: 1.7_dev
main: com.massivecraft.factions.P
authors: [Olof Larsson, Brett Flannigan]
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, nChat, ChatManager, CAPI, AuthMe, Register, Spout, WorldEdit, WorldGuard]
commands:
  factions:
    description: Reference command for Factions.
    aliases: [f]
permissions:
  factions.kit.admin:
    description: All faction permissions.
    children:
      factions.kit.mod: true
      factions.config: true
      factions.lock: true
      factions.reload: true
      factions.save: true
  factions.*:
    description: This is just an alias for factions.kit.admin
    children:
      factions.kit.admin: true
  factions.kit.mod:
    description: All faction permissions but configuration and persistance.
    children:
      factions.kit.halfmod: true
      factions.disband.any: true
      factions.sethome.any: true
      factions.money.*: true
  factions.kit.halfmod:
    description: Zones, bypassing, and kicking
    children:
      factions.kit.fullplayer: true
      factions.bypass: true
      factions.flag.any: true
      factions.perm.any: true
      factions.kick.any: true
  factions.kit.fullplayer:
    default: true
    description: Can also create new factions.
    children:
      factions.kit.halfplayer: true
      factions.create: true
  factions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      factions.leader: true
      factions.autoclaim: true
      factions.chat: true
      factions.claim: true
      factions.deinvite: true
      factions.description: true
      factions.disband: true
      factions.flag: true
      factions.perm: true
      factions.help: true
      factions.home: true
      factions.invite: true
      factions.join: true
      factions.kick: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.officer: true
      factions.money.kit.standard: true
      factions.open: true
      factions.power: true
      factions.power.any: true
      factions.relation: true
      factions.sethome: true
      factions.show: true
      factions.tag: true
      factions.title: true
      factions.version: true
      factions.unclaim: true
      factions.unclaimall: true
  factions.leader:
    description: hand over your leader rights
  factions.autoclaim:
    description: auto-claim land as you walk around
  factions.bypass:
    description: enable admin bypass mode
  factions.chat:
    description: change chat mode
  factions.claim:
    description: claim land where you are standing
  factions.config:
    description: change a conf.json setting
  factions.create:
    description: create a new faction
  factions.deinvite:
    description: remove a pending invitation
  factions.description:
    description: change the faction description
  factions.disband:
    description: disband a faction
  factions.disband.any:
    description: disband an other faction
  factions.flag:
    description: change faction flags
  factions.flag.any:
    description: change all flags for all factions
  factions.perm:
    description: change faction permissions
  factions.perm.any:
    description: change all permissions for all factions
  factions.help:
    description: display a help page
  factions.home:
    description: teleport to the faction home
  factions.invite:
    description: invite a player to your faction
  factions.join:
    description: join a faction
  factions.kick:
    description: kick a player from the faction
  factions.kick.any:
    description: kick anyone from any faction
  factions.leave:
    description: leave your faction
  factions.list:
    description: see a list of the factions
  factions.lock:
    description: lock all write stuff
  factions.map:
    description: show the territory map, and set optional auto update
  factions.officer:
    description: give or revoke officer rights
  factions.money.balance:
    description: show your factions current money balance
  factions.money.balance.any:
    description: show money balance for factions other than your own
  factions.money.deposit:
    description: deposit money into a faction bank
  factions.money.withdraw:
    description: withdraw money from your faction bank
  factions.money.withdraw.any:
    description: withdraw money from your factions other than your own
  factions.money.f2f:
    description: transfer money from faction to faction
  factions.money.f2p:
    description: transfer money from faction to player
  factions.money.p2f:
    description: transfer money from player to faction
  factions.money.kit.standard:
    children:
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  factions.money.*:
    children:
      factions.money.kit.standard: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.withdraw.any: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  factions.open:
    description: switch if invitation is required to join
  factions.power:
    description: show player power info
  factions.power.any:
    description: view an other players power level
  factions.relation:
    description: set relation wish to another faction
  factions.reload:
    description: reload data file(s) from disk
  factions.save:
    description: save all data to disk
  factions.sethome:
    description: set the faction home
  factions.sethome.any:
    description: set faction home for another faction
  factions.show:
    description: show faction information
  factions.tag:
    description: change the faction tag
  factions.title:
    description: set or remove a players title
  factions.version:
    description: see the version of the plugin
  factions.unclaim:
    description: unclaim the land where you are standing
  factions.unclaimall:
    description: unclaim all of your factions land